# Default values for snacker-tracker-recorder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.k8s.fscker.org/snacker-tracker/reporter
  # README: lets keep .Values.tag null so that we can selectively override
  # the image tag. We'll be defaulting to the application version as docker image
  # tag anyway. See:
  #   https://github.com/snacker-tracker/reporter/blob/master/helm-charts/snacker-tracker-reporter/templates/deployment.yaml#L27
  # tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  # I prefer keeping the service port and ports on the containers distinct.
  # See: https://github.com/snacker-tracker/reporter/blob/master/helm-charts/snacker-tracker-reporter/templates/deployment.yaml#L27
  internal_port: 5000

ingress:
  enabled: false
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
    certmanager.k8s.io/cluster-issuer: lets-encrypt-prod
  hosts:
    - host: chart-example.local
      paths: []

  tls: []

resources:
  requests:
    cpu: 0.01
    memory: 128Mi

postgresql:
  enabled: true
  service:
    port: 5432

nodeSelector: {}

tolerations: []

affinity: {}

config:
  env:
    PORT: "5000"
