apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forum-api.fullname" . }}
  labels:
    # NON-DEFAULT: We also care about knowing the version of the app.
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
{{ include "forum-api.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
