apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "forum-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "forum-api.name" . }}
    helm.sh/chart: {{ include "forum-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    # NON-DEFAULT: We also care about knowing the version of the app.
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
stringData:
{{- range $key, $value := .Values.config.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
